### PR TITLE
Coveralls added

### PR DESCRIPTION
**Pull request by larathordar**
Pull Request template.

#### Description
Changes proposed in this pull request:

*Coveralls added to check test coverage

#### What I have learned working on this feature:
* I learned to add coveralls and connect it with semaphore

### CODE REVIEW

**Review by tochman — CHANGES_REQUESTED** [review]
Can't see how this will track metrics for bort RSpec and Cucumber

**Review by holgertidemand — COMMENTED** [review]
Looks good to me!

**Comment by jyuw** [comment]
looks good guys!

**Review by tochman — APPROVED** [review]
Good job

**Pull request merged**
