### PR TITLE
Continuous Integration and Deployment

### PR DESCRIPTION
**Pull request by jyuw**
## Description
Changes proposed in this pull request:
* added back listen gem for Semaphore 
* implemented Semaphore successfully
* connected Heroku for automatic deployment

What I have learned working on this feature:
* how to use Semaphore
* Semaphore > Travis
* how to deploy with heroku through semaphore

### CODE REVIEW

**Comment by larathordar** [comment]
It looks beautiful

**Comment by larathordar** [comment]
listen gem should be in group : development do
see  below 

```
group :development do
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

**Comment by larathordar** [comment]
looks good now

**Comment by magnus-thor** [comment]
Looks good.

**Pull request merged**
