### PR TITLE
Bug fix: error message displayed for edit article feature

### PR DESCRIPTION
**Pull request by jyuw**
#### PT Story: 
bug fix PT: https://www.pivotaltracker.com/story/show/156129727
original PT: https://www.pivotaltracker.com/story/show/155897981
#### Description
Changes proposed in this pull request:

* adds `local: true` to `form_with` line in the edit view so that the error message displays correctly

#### What I have learned working on this feature:
* remember to add `local: true` to `form_with` forms

#### Screenshots:
screen shot 2018-03-19 at 7 36 08 pm

### CODE REVIEW

**Review by tochman — CHANGES_REQUESTED** [review]
I need to see this in action. Flashes have always worked for me with `render`. Also, the team needs to discuss how bugs are being handled before worked on.

**Review by larathordar — APPROVED** [review]
Looks fantastic. Good job.

**Comment by kmthorsnes** [comment]
Looks good to me.

**Review by kmthorsnes — APPROVED** [review]
looks good to me

**Review by tochman — APPROVED** [review]

**Pull request merged**
