### PR TITLE
Categories only show up once per article

### PR DESCRIPTION
**Pull request by holgertidemand**
#### Description
Changes proposed in this pull request:

* Articles can only have one instance of a category

#### What I have learned working on this feature:
* checking for existing instances of categories
* writing proper sad paths

### CODE REVIEW

**Comment by tochman** [comment]
See comment on PT

**Comment by diraulo** [comment]
In general, if you write good acceptance tests, you can catch most of these bugs too @holgertidemand 

The problem is that most of the time you only focus on writing Happy path scenarios and don't consider sad paths for all your features.

**Review by tochman — APPROVED** [review]
Looks good to me.

**Review by kmthorsnes — APPROVED** [review]
Looks good to me

**Pull request merged**
